{% set name = "venn-abers" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/venn-abers-{{ version }}.tar.gz
  sha256: fb522b710ec22bc04adda1cbb78c7c6c8c07edde283286a43e04be051e45722e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scikit-learn

test:
  imports:
    - venn_abers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ip200/venn-abers
  summary: Venn-ABERS calibration package
  license: MIT
  license_file: LICENSE.TXT

extra:
  recipe-maintainers:
    - ip200
